### PR TITLE
Separated build files from source code, improved scripts

### LINKED ISSUE #10: Publishing Package
- put JS in one folder: `tsconfig.json`: `"outDir": "dist"`
- publish this code: `package.json`: `"files": [
    "dist"
  ]`
- `.gitignore` only has mention `dist`

However, when importing the module with yalc there are errors:
```
 yalc add @knora/api && npm i
Package @knora/api@0.0.1-541826c4 added ==> knora-api-js-lib-test/node_modules/@knora/api.
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/source-map-25a4383f/lib/source-map-generator.js'
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/pako-f746448f/dist/pako_inflate.min.js'
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/source-map-25a4383f/lib/source-node.js'
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/source-map-25a4383f/lib/util.js'
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/pako-f746448f/dist/pako.js'
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/@angular/compiler-c28c8617/esm2015/src/output/output_interpreter.js'
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/typescript-35282e12/lib/tsserver.js'
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/typescript-136b0557/lib/tsserverlibrary.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'knora-api-js-lib-test/node_modules/.staging/@angular/core-732fdb93/fesm5/core.js.map'
npm ERR! path knora-api-js-lib-test/node_modules/.staging/@knora/api-b29e8d31/node_modules/rxjs
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'knora-api-js-lib-test/node_modules/.staging/@knora/api-b29e8d31/node_modules/rxjs' -> 'knora-api-js-lib-test/node_modules/.staging/rxjs-6aa6c640'
npm ERR! enoent This is related to npm not being able to find a file.

```

### PR DESCRIPTION
**Pull request by andreas-aeschlimann**
As discussed, I separated build files from source code. All build files go into a `build` folder, tarball packages go into a `dist` folder.

Further details cited from the ReadMe update in this commit:

> This package provides the following short-hand scripts:
> 
> 1. `npm run test`: Runs the project's tests defined in `./karma.conf.js`. The coverage data is saved into the `./coverage/` folder.
> 2. `npm run build`: Builds the whole project without testing and puts the files into the `./build/` folder.
> 3. `npm run yalc-publish`: Executes 2 and publishes the package to the yalc app store.
> 4. `npm run npm-pack`: Executes 1, 2 and packs the `./build/` folder into an NPM tgz package. The package is moved into a `./dist/` folder.
> 5. `npm run npm-publish`: Executes 4 and publishes the package to the NPM store.

This pull request closes #10.

### CODE REVIEW

**Comment by andreas-aeschlimann** [comment]
Did you run `npm install` after the checkout? 

This PR uses the package `copyfiles` as dev-dependency. If the build script fails to copy the files (because copyfiles is missing), it will fail to make a proper build.

On another note, I could replace the `copyfiles` command with `cp`, then the package is not required anymore.

**Comment by tobiasschweizer** [comment]
> Did you run npm install after the checkout?

Now I did and it works, thanks. 

However, I tried to reproduce this without having `copyfiles` installed and I got:
`sh: copyfiles: command not found`

**Comment by andreas-aeschlimann** [comment]
I removed the dependency of copyfiles. It's better not to have more dependencies.

What do you think about this new commit without copyfiles?

It will not work on Windows with cp, however. Do you think that is an issue?

**Comment by tobiasschweizer** [comment]
> It will not work on Windows with cp, however. Do you think that is an issue?

No, I don't think so.

**Pull request merged**
