### PR TITLE
Integrate v2 test data

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR adds a script to automate the integration of v2 test data.

Needed for #47 and #41

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@benjamingeer This is a simple way to keep the test data in sync. It just copies JSON test data files from the Knora v2 E2E tests. I would like all tests to be based on the anything project. I would need to produce more test data for anything, like ontologies, lists etc. 

I could just add some more E2E tests to Knora. Would that be ok?

**Comment by tobiasschweizer** [comment]
> Would it be more maintainable if it had a config file specifying the source and destination paths?

That would be the first step, probably we want to have a process like for the admin API with a special route.

**Comment by tobiasschweizer** [comment]
@benjamingeer I think I could rewrite that script in JS to be run by node. The config could live in a JSOn file.

**Comment by benjamingeer** [comment]
I think you'll be happier with it in Node (or Python) than in Bash.

**Comment by tobiasschweizer** [comment]
> I think you'll be happier with it in Node (or Python) than in Bash.

I think the effect on my mental health will be minimal ;-)

**Comment by tobiasschweizer** [comment]
done in https://github.com/dhlab-basel/knora-api-js-lib/pull/56/commits/cc333efc0f299124619ad94a2498ea71211a8320 (please note the commit message)

**Pull request merged**
